[build]
  command = "git clone https://github.com/flutter/flutter.git && export PATH=\"$PWD/flutter/bin:$PATH\" && flutter config --enable-web && flutter pub get && flutter build web"
  publish = "build/web"